Upgrade codes related to IAM, DDB and Kinesis clients
Update source files

Update test files

Fix initialization errors during tests

Remove RegionUtil usages and fix Guava NoSuchMethodError

Update guava version

Update KinesisUtilsPythonHelper

Upgrade AWS SDK to v2 in kubernetes test module

Remove tags

Update kinesis docs

Remove sdk dependency in core module

Remove unused import